# Generated by Django 5.2.8 on 2026-01-31 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='interview_at',
        ),
        migrations.AddField(
            model_name='jobposition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='salary_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='cv_file',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposition'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_jobseeker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
