# Generated by Django 5.2.8 on 2026-01-31 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_resume_interview_at_jobposition_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='description',
            field=models.TextField(default='', verbose_name='توضیحات شغل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposition',
            name='location',
            field=models.CharField(default='', max_length=150, verbose_name='موقعیت مکانی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='interview_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان مصاحبه'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='benefits',
            field=models.TextField(blank=True, null=True, verbose_name='مزایا و تسهیلات'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارفرما'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='آگهی فعال باشد؟'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='requirements',
            field=models.TextField(verbose_name='نیازمندی\u200cها'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='salary_min',
            field=models.IntegerField(verbose_name='حداقل حقوق (تومان)'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='cv_file',
            field=models.FileField(upload_to='resumes/', verbose_name='فایل رزومه'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposition', verbose_name='شغل درخواستی'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='کارجو'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('rejected', 'رد شده'), ('interview', 'دعوت به مصاحبه')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False, verbose_name='کارفرما است'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_jobseeker',
            field=models.BooleanField(default=False, verbose_name='کارجو است'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن'),
        ),
    ]
