# Generated by Django 5.2.8 on 2025-11-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_resume_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='interview_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان مصاحبه'),
        ),
    ]
