# Generated by Django 5.2.8 on 2025-12-03 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_resume_interview_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='مدیر شرکت')),
            ],
        ),
        migrations.AddField(
            model_name='jobposition',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company', verbose_name='شرکت'),
        ),
    ]
