# Generated by Django 5.2.8 on 2026-02-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مصاحبه'),
        ),
    ]
